### PR TITLE
Add locales (french)

### PR DESCRIPTION
**Pull request by wmai**

### CODE REVIEW

**Comment by mongkok** [comment]
Hi @wmai :),
I'm sorry for the delay in my response.

Could you also include the locales for the `graphql_jwt/refresh_token` submodule?

Thanks!

**Comment by wmai** [comment]
Hi @mongkok,

Sure, I'll do it ASAP.

**Comment by abumalick** [comment]
@mongkok What do you think about merging this PR ASAP and finish the work in a new PR ?

I think it is better to have half translations than nothing ...

**Comment by abumalick** [comment]
Thank you very much @mongkok , I will probably push a PR tomorrow for Arabic

**Pull request merged**
