### PR TITLE
PyJWT>=1.5.0,<2'

### PR DESCRIPTION
**Pull request by rganeyev**
Prevent from installing PyJWT v2 as it breaks compatibility

### CODE REVIEW

**Comment by balazss** [comment]
Awesome. Can someone merge? 🙂

**Comment by ulgens** [comment]
@balazss I'm not sure this repo is still alive. I'm planning to fork it tbh.

**Comment by laurent-brisbois** [comment]
> @balazss I'm not sure this repo is still alive. I'm planning to fork it tbh.

If you plan to do so and maintain it, please warn us ;-)

**Comment by thongly** [comment]
Maybe we should ask devs to become maintainers of this repo as well, instead of forking.  It makes more sense to work together if at all possible.

2 weeks is a bit long for a 1-line change to merge, but admittedly, 3 days after this was pushed (and over the holidays) is understandable.

**Review by ahter — APPROVED** [review]

**Comment by ahter** [comment]
I believe we can wait some more as this time of year is right after the holidays and people are very busy these days.

**Comment by rganeyev** [comment]
Is there any update? This repo is still broken for month!

**Comment by laurent-brisbois** [comment]
> Is there any update? Can anyone merge? This repo is still broken for month!

I think this repo is kinda dead actually...

**Comment by thongly** [comment]
If someone will fork and add a few of us as contributors, I'd be happy to pitch in. In my opinion, it's important to make sure we're all working on the same repo, even if it's new, so that another slower death isn't inevitable.

I wonder if we can push this to a [jazzband](https://github.com/jazzband) repo or something.

**Comment by ulgens** [comment]
@rganeyev @laurent-brisbois @thongly I forked this package last week and trying to start an organization to maintain couple another dead packages. I'll announce it soon.

**Comment by thongly** [comment]
> @rganeyev @laurent-brisbois @thongly I forked this package last week and trying to start an organization to maintain couple another dead packages. I'll announce it soon.

Yeah - let's do it! Let's just make sure we keep it open and alive going forward, whether Jazzband or not.

**Comment by mongkok** [comment]
I apologize for the delay in my response #261.
The new release requires Graphene v3 and supports PyJWT>=2:
```sh
pip install 'django-graphql-jwt>=0.3.2'
```

**Pull request closed without merging**
