### PR TITLE
feat: add arabic translations

### PR DESCRIPTION
**Pull request by abumalick**
add arabic translations

### CODE REVIEW

**Comment by abumalick** [comment]
@mongkok Please we need this one for our project.

Thank you very much

**Comment by abumalick** [comment]
@mongkok review please, thank you very much

**Comment by mongkok** [comment]
Hi @abumalick ,
Please, remove the path prefix `graphql_jwt`.
e.g. `graphql_jwt/decorators.py:91` -> `decorators.py:91`.

**Comment by abumalick** [comment]
here you go @mongkok 
I made the same change for the FR translation PR.

These path were added automatically by django-admin

**Comment by abumalick** [comment]
@mongkok Don't forget us, please

thank you very much

**Comment by mongkok** [comment]
Thanks @abumalick.

**Comment by abumalick** [comment]
thank you too for providing these very useful packages @mongkok 👍

**Pull request merged**
