### PR TITLE
Token cannot be created ('str' has no attribute 'decode')

### LINKED ISSUE #241: Token cannot be created ('str' has no attribute 'decode')
I've recently started to incorporate GraphQL into one of my existing projects. Installed django-graphql-jwt according to the documentation but whenever I run the below, I get the following error:

`mutation {
  tokenAuth(
    username: "dummy",
    password: "dummydummy"
  ) {
    token
  }
}`

`{
  "errors": [
    {
      "message": "'str' object has no attribute 'decode'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "tokenAuth"
      ]
    }
  ],
  "data": {
    "tokenAuth": null
  }
}`

I've searched almost everywhere but I cannot track down what the issue and as far as I can see it should work?

Relevant pieces of code:
Settings.py
```GRAPHENE = {
    "SCHEMA": "blackbook.schema.schema",
    "MIDDLEWARE": [
        "graphql_jwt.middleware.JSONWebTokenMiddleware",
        "graphene_django.debug.DjangoDebugMiddleware",
    ],
}
```

Blackbook.schema
```import graphene
import graphql_jwt

from .api import user


class Query(user.Query, graphene.ObjectType):
    pass


class Mutation(graphene.ObjectType):
    token_auth = graphql_jwt.ObtainJSONWebToken.Field()
    verify_token = graphql_jwt.Verify.Field()
    refresh_token = graphql_jwt.Refresh.Field()


schema = graphene.Schema(query=Query, mutation=Mutation)```
```

### PR DESCRIPTION
**Pull request by rasheedhamdawi**
Fix #241

### CODE REVIEW

**Review by rganeyev — APPROVED** [review]
I confirm this works for registering and authentication

**Comment by JazabC** [comment]
When will this fix be merged?

**Comment by rganeyev** [comment]
The problem is deeper, PyJWT is incompatible with the current implementation. I suggest downgrading PyJWT lib to 1.* version.

**Review by rganeyev — CHANGES_REQUESTED** [review]
Problem is deeper, I suggest downgrading to PyJWT 1.* to fix it #244

**Comment by rasheedhamdawi** [comment]
Yes,  PyJWT is incompatible with the current implementation.
But this solution will make it works for both PyJWT 1 and PyJWT 2

**Comment by thongly** [comment]
Looks like the maintainers were just a bit bogged down over the holidays.

Could some others join as maintainers and/or could we get a quick review of the dangling PR's?  Thanks.

**Comment by ulgens** [comment]
@thongly There is no other maintainer. The only person in the flavors organization is @mongkok and I can't find his contact info.

**Comment by thongly** [comment]
@ulgens - Makes sense. I [had a quick look and couldn't find him](https://www.google.com/maps/@22.3193121,114.1691624,3a,75y,190.09h,90t/data=!3m7!1e1!3m5!1sOzGr2tMS8TM-0H4Xag4qPQ!2e0!6s%2F%2Fgeo1.ggpht.com%2Fcbk%3Fpanoid%3DOzGr2tMS8TM-0H4Xag4qPQ%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D189.35081%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192).

If someone wants to fork, maybe we can all jump on the same repo at least.

Hopefully when @mongkok is back, we can merge back in to a single repo, or make one the official repo going forward if there's no further maintenance here.

**Comment by ulgens** [comment]
To update everyone here, I found his email address with some help from graphene community and mailed him. I'll update this discussion when I have a reply or passed enough time without an answer.

**Comment by mongkok** [comment]
I apologize for the delay in my response #261.
The new release requires Graphene v3 and supports PyJWT>=2:
```sh
pip install 'django-graphql-jwt>=0.3.2'
```

**Pull request closed without merging**
