### PR TITLE
Remove usage of deleted packages

### LINKED ISSUE #150: Django 3.0 incompatibility
Django just released version 3 of their framework https://docs.djangoproject.com/en/3.0/releases/3.0/

One change is : 
> django.utils.six - Remove usage of this vendored library or switch to six.
> django.utils.encoding.python_2_unicode_compatible() - Alias of six.python_2_unicode_compatible().

This breaks this library because it does import six in some places.

Is there anything I can do to get this fixed?

### PR DESCRIPTION
**Pull request by lassesteffen**
Fixes #150 
- remove all usages of six
- drop python 2 compatibility

> Since we expect apps to drop Python 2 compatibility when adding support for Django 3.0, we’re removing these APIs at this time.

### CODE REVIEW

**Comment by valberg** [comment]
Can we do anything to move this along?

**Comment by oldani** [comment]
Wating for this to upgrade to Django 3.0

**Comment by lassesteffen** [comment]
If this library accepts these changes the test suite should also be adjusted, if anybody can give me a hint I am willing to change this

**Comment by valberg** [comment]
> If this library accepts these changes the test suite should also be adjusted, if anybody can give me a hint I am willing to change this

What do you mean @lassesteffen? Seems like the tests pass just fine for this PR?

**Comment by lassesteffen** [comment]
It should also test explicitly for Django 3 right?

**Comment by valberg** [comment]
Ah yes of course! Didn't think of that! I can do a PR that does that.

**Comment by valberg** [comment]
@lassesteffen Now Django 3.0 is being tested in my PR: https://travis-ci.org/flavors/django-graphql-jwt/builds/620524261

@mongkok Do you need any help with getting a new release out? I'm happy to help :)

**Pull request merged**
