### PR TITLE
dont be snippy in user feedback

### PR DESCRIPTION
**Pull request by fivethreeo**
Please, enter valid credentials. no comma :)

### CODE REVIEW

**Comment by mongkok** [comment]
Thanks @fivethreeo ,
Could you update the locales?

**Comment by fivethreeo** [comment]
Done :)

**Comment by mongkok** [comment]
Hey @fivethreeo ,
You've removed all code paths.
e.g. https://github.com/flavors/django-graphql-jwt/pull/142/files#diff-d8ab124e99707f80d99fd4ba0524caedL26

**Comment by fivethreeo** [comment]
Readded code paths :)

**Comment by mongkok** [comment]
Thanks @fivethreeo !

**Pull request merged**
